#! /bin/sh

set -xeu

package_set="$1"
shift
commit="$( cat commits/"$package_set".tip )"

nixpkgs_repo=~/repos/nixpkgs
cd "$nixpkgs_repo"
git checkout "$commit"
cd - > /dev/null

export NIX_PATH=nixpkgs="$HOME"/repos/nixpkgs
nix-env \
  -f ./package_sets/"$package_set".nix \
  "$@" \
  -i
