#! /bin/sh

set -e

# Avoid warnings from Perl about unset `LC_ALL`.
#
if [ -z "$LC_ALL" ]; then
   export LC_ALL=C
fi

set -u

git submodule update --init --recursive

packages='cvs git hg password-store tmux upshell vim'

for stowdir in $packages
do
   echo "Stowing $stowdir..."
   stow --target=$HOME "$stowdir"
done
