#! /bin/sh

set -e

# Avoid warnings from Perl about unset `LC_ALL`.
#
if [ -z "$LC_ALL" ]; then
   export LC_ALL=C
fi

set -u

git submodule update --init --recursive

for stowdir in $( find . -maxdepth 1 -type d | sed 's/^..//' )
do
   echo "Stowing $stowdir..."
   stow --target=$HOME "$stowdir"
done
